env:
  global:
  - GIT_COMMITTER_NAME=y-kurami
  - GIT_COMMITTER_EMAIL=yosuke.kurami@gmail.com
  - GIT_AUTHOR_NAME=Quramy
  - GIT_AUTHOR_EMAIL=yosuke.kurami@gmail.com
language: node_js
node_js:
- 0.12.4
before_install:
- npm install -g gulp
- npm install
script:
- gulp test
deploy:
  provider: npm
  email: yosuke.kurami@gmail.com
  api_key:
    secure: mc8TWn1BmGQ5OvA+cwvys48/OPGY8EP608DyxTiDq1gb5CKuuNFCmQ92EAY5IekHmq7b6yqgIJjeEZchRgBssNyHbV5n1eEXLPmt8pCoMDecj72fnG/7GwNSk18vOesH5XtRWpAG+QW3Rdeg+yejZt+EvAOpJk0p8AzIrA8IlOY8GhAOq9uf7QR76YVUGYoNM9MEtYOa1veAbBuVNehj+ESWOkhho3oOq40CxXWkj865607do+MSi7/L9LBYAOVyVraq6eadE+Xo9DS4NdymyQf9BeHf+r6Pxswz2NGTZORZ2sK8Qb2Xx078AEytfleLt4NqnslcdzxFfVsBPQGdz3X58S1KcplJ0QA45QC95GGu8mw2VuLg1hLWq6Wi/TSBXTsfOyNWtd5kKmjbqMxcXLuySxSK8V+8tZH8sC5usCO834RQpoTT1Zsn7hCTNsceEELyjyOkFdD5UqnIsrKg/jkWsy22i/F5GyOkikPqIJdnqogwxnZnnUmoFxX3im5kRBT8fSGqWfTumzH6eRz0YTm6f+76WkbtokZzOOmwEcQqZG3zCmF0XN1zJj5ITi4yYnhcfPEJErOrb9aaYaRvdjeG/N1JjrzlWTxPo7vwt5/C+47XyX5fKiAd38IEsOMZN+iMcfNBq4Sb2EX/wvGtGEyTEpzd13FUQPpTrZUax0g=
  on:
    tags: true
    repo: Quramy/electron-connect
