env:
  global:
  - GIT_COMMITTER_NAME=y-kurami
  - GIT_COMMITTER_EMAIL=yosuke.kurami@gmail.com
  - GIT_AUTHOR_NAME=Quramy
  - GIT_AUTHOR_EMAIL=yosuke.kurami@gmail.com
language: node_js
node_js:
- 0.12.4
before_install:
- npm install -g gulp
- npm install
script:
- gulp test
deploy:
  provider: npm
  email: yosuke.kurami@gmail.com
  api_key:
    secure: PPAPHiPRjFz9IvFMNrP8Yoq7Dm/t6cJI96Wlz7e2n4onjrnp4kqhvwVMExLeYQq3Juj2Li90uZRrA6GsfUCAVfE7aRngwst9+8TpvLuGCaTWwK5wT10FU5rY4c8Rv8fdYy45eHfmvrXVeH7jPt1p4ZdkyvlgbdeImFqE5/ftXvUjbM4lfq+lv4WE/St2PYusc5tcjblCmbxbPgZn8ERsfSQRzdHW7CodvYXVoK15AICpIpz7B5N5B1KXNtlXcVbo+nIPWo/rx/hEVxcQ+DHBR0Qtm5U9xkt1J3LLrZCNTe47ejJT38YKljXmkO5qEOP/IVdua0L03f99ajd4S4g+0zUhpEovzqhpIRP50UpTgc8AKvgz8ZyFDIrE44e7I9AxqlHiaHAMBn3CqPwAbDBYedA11nuv05pP7tKHciW07zunHEGVO0ZZn68H95a0eQdEJ48/MSaHsgnI+RWSfgqCoPR3L+knPp2eT0dyzq1lxnLPhTDcikwgJa3G88dnP1v3vnZdHYq56Ensa/fZ+49JmN3yrrI9ZuYn76+DxMAUImyQoCZTzlDXnM4Cznn6jZk3tXb6m8ZTrbhx4vD8rafwudSTWKLAdus++ukb/ROebcxhQtGHwdksCpMAwNvDY1GGnVrAyA2HPA+eLNI4ILXs0AIGCzAwTNJPw8fzLwVaBSg=
  on:
    tags: true
    repo: Quramy/electron-connect
